language: python

notifications:
    email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

addons:
  apt:
    packages:
    # - sox
    - libsndfile1

before_install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget http://repo.continuum.io/miniconda/Miniconda2-4.3.21-Linux-x86_64.sh -O miniconda.sh;
      else
          wget http://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
#    - conda update -q conda
    - conda info -a
#    - deps='pip atlas numpy scipy sphinx nose six future pep8 matplotlib decorator'
    - deps='pip numpy scipy'
    - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" $deps
    - source activate test-environment
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          pip install pytest==4.6.0 PyYAML==4.2b4 pytest-faulthandler==1.6.0;
      fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
          pip install pytest==4.6.0 PyYAML==4.2b4 pytest-faulthandler==1.6.0;
      fi
    - conda install -c conda-forge ffmpeg
    - conda install -c conda-forge sox
    - pip install python-coveralls
    - pip install pytest-faulthandler
    - pip install pytest-cov
#    - pip install numpydoc

install:
    - pip install -e .[tests]

#before_script:
#    - pep8 mir_eval evaluators tests

script:
#    - nosetests -v --with-coverage --cover-package=mir_eval
#    - python setup.py build_sphinx
#    - python setup.py egg_info -b.dev sdist --formats gztar
     - py.test

after_success:
    - coveralls
